export const BACKEND_ACCORDS = [
  "Fresh",
  "Citrus",
  "Fruity",
  "Sweet",
  "Floral",
  "Powdery",
  "Creamy",
  "Gourmand",
  "Oriental",
  "Spicy",
  "Animal",
  "Leathery",
  "Smoky",
  "Woody",
  "Resinous",
  "Earthy",
  "Chypre",
  "Fougère",
  "Green",
  "Aquatic",
  "Synthetic",
] as const;

export const DISPLAY_ACCORDS = [
  "Fresh",
  "Citrus",
  "Fruity",
  "Sweet",
  "Floral",
  "Powdery",
  "Creamy",
  "Gourmand",
  "Oriental",
  "Spicy",
  "Animal",
  "Leathery",
  "Smoky",
  "Woody",
  "Resinous",
  "Earthy",
  "Chypre",
  "Fougère",
  "Green",
  "Aquatic",
  "Synthetic",
] as const;

export const ACCORD_COLORS: Record<(typeof BACKEND_ACCORDS)[number], string> = {
  Fresh: "#8FB5FF",
  Citrus: "#E6E04A",
  Fruity: "#F39A4C",
  Sweet: "#F4A3C4",
  Floral: "#F6B3C6",
  Powdery: "#E9CFCF",
  Creamy: "#F1E8D6",
  Gourmand: "#B97A4B",
  Oriental: "#7A3E2F",
  Spicy: "#9E3B32",
  Animal: "#7A5C3E",
  Leathery: "#2E2B28",
  Smoky: "#7B7B7B",
  Woody: "#6B4F2A",
  Resinous: "#4B6F8A",
  Earthy: "#AD868B",
  Chypre: "#3F6F5E",
  "Fougère": "#6F7A4A",
  Green: "#4FA66A",
  Aquatic: "#5FBED7",
  Synthetic: "#7FA1D6",
};

/** 어코드 한글명 매핑 */
export const ACCORD_LABELS: Partial<Record<(typeof BACKEND_ACCORDS)[number], string>> & Record<string, string> = {
  Animal: "애니멀",
  Aquatic: "아쿠아틱",
  Chypre: "시프레",
  Citrus: "시트러스",
  Creamy: "크리미",
  Earthy: "얼씨",
  Floral: "플로럴",
  Fougère: "푸제르",
  Fruity: "프루티",
  Gourmand: "구르망",
  Green: "그린",
  Leathery: "레더리",
  Oriental: "오리엔탈",
  Powdery: "파우더리",
  Resinous: "수지향",
  Smoky: "스모키",
  Spicy: "스파이시",
  Sweet: "스위트",
  Synthetic: "인공향",
  Woody: "우디",
  Fresh: "프레시",
};

/** 어코드 설명 */
export const ACCORD_DESCRIPTIONS: Partial<Record<(typeof BACKEND_ACCORDS)[number], string>> & Record<string, string> = {
  Animal: "체온이 느껴지는 깊은 향, 살에 가까이 붙는 따뜻함, 은근히 관능적인 분위기",
  Aquatic: "바닷가에 서 있는 듯한 시원함, 바람에 실린 물 냄새, 맑고 차가운 느낌",
  Chypre: "숲속 땅을 밟았을 때의 냄새, 이끼와 흙이 섞인 차분함, 조용하지만 고급스러운 분위기",
  Citrus: "막 껍질을 깐 과일 향, 밝고 경쾌한 느낌, 처음 맡자마자 기분 좋아지는 상쾌함",
  Creamy: "부드럽고 포근한 느낌, 크림이나 우유 같은 질감, 자극 없이 편안한 달콤함",
  Earthy: "비 온 뒤 흙 냄새, 자연 그대로의 묵직함, 안정감 있는 차분한 분위기",
  Floral: "꽃이 만개한 정원 같은 향, 부드럽고 화사함, 로맨틱하고 밝은 인상",
  Fougère: "숲속을 걷는 듯한 향, 풀과 나무가 섞인 자연스러움, 상쾌하면서도 단정한 느낌",
  Fruity: "잘 익은 과일 향, 달콤하고 생기 있는 느낌, 발랄하고 상큼한 분위기",
  Gourmand: "디저트가 떠오르는 향, 달콤하고 따뜻함, 고소하고 포근한 느낌",
  Green: "풀잎을 비볐을 때의 냄새, 생생하고 자연스러움, 인공적이지 않은 신선함",
  Leathery: "새 가죽 제품의 냄새, 단단하면서도 부드러움, 성숙하고 묵직한 인상",
  Oriental: "사막의 더운 느낌, 진하고 화려한 분위기, 밤에 잘 어울리는 향",
  Powdery: "파우더를 바른 듯한 향, 보송하고 부드러움, 차분하고 깨끗한 느낌",
  Resinous: "끈적한 나무 수액 같은 향, 진하고 따뜻함, 묵직하게 남는 잔향",
  Smoky: "불 근처에 있었던 옷 냄새, 그을린 듯한 느낌, 마초적인 분위기",
  Spicy: "코끝을 살짝 자극하는 향, 따뜻하고 생동감 있음, 향에 긴장감을 더해주는 느낌",
  Sweet: "설탕이나 꿀 같은 달콤함, 부드럽고 기분 좋아지는 향, 친근하고 따뜻한 분위기",
  Synthetic: "새 제품을 처음 열었을 때의 냄새, 또렷하고 인공적인 깨끗함, 현대적이고 세련된 느낌",
  Woody: "나무 가구나 숲을 떠올리게 하는 향, 단단하고 안정적인 느낌, 차분하고 무게감 있는 분위기",
  Fresh: "샤워 후처럼 깨끗한 느낌, 공기가 맑아진 듯한 향, 가볍고 시원한 분위기",
};
